name: tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate project from cookiecutter
        run: pip install cookiecutter && cookiecutter --no-input -f ./ project_name="Testing Project"
      - name: Install poetry
        run: pip install poetry && poetry config virtualenvs.create false
      - name: Install dependencies
        run: cd ./testing-project && poetry install
      - name: tests
        run: pytest tests/
